new data format and mean plot
yeatmanlab/AFQ-Browser pull request #30
Opened 2016-09-26 00:51 UTC by anotherjoshsmith

changed data.csv to new format and added initial whole population mean plots for each tract

2016-09-26 17:09 UTC, richford commented on client/js/tract-details.js
>    }
This change broke the brushing behavior. But I think the fix is simple. Here is one extra closing bracket which closes the ready function. It should be moved below.

2016-09-26 17:09 UTC, richford commented on client/js/tract-details.js
> +
That extra closing bracket should be moved here so that all the brushing functions are in the same scope as the d3.brush.

2016-09-26 17:10 UTC, richford requested changes

2016-09-26 17:15 UTC, anotherjoshsmith commented on client/js/tract-details.js
> +
sorry about that, good catch!

2016-09-28 18:30 UTC, richford approved these changes

2016-09-28 19:07 UTC, arokem commented
For column headers, take a look at this table, and the way the cursor changes when hovering over column headers: http://bl.ocks.org/crevoisiersabine/34cef262b6632d82e4a6

2016-10-03 19:00 UTC, arokem commented
Before we can merge, need to fix: 
- [ ] Selection and deslection of individual lines/subjects
- [ ] Yoke the controls to the appearance of the plots

2016-10-14 23:14 UTC, closed without merging

2016-10-14 23:15 UTC, anotherjoshsmith commented
Shifted work to split_plot branch.

2016-10-14 23:16 UTC, arokem commented
Superseded by #42